package com.whut.crawler;

import java.util.Random;

/**
 * @author Bruce
 * @date 2017/11/27
 */
public class GanjiCrawlerUtils {

    private String CITY_TEST[] = {"bazhong"};

    public static  String CITY_LIST[] = {
            "anshan",
//            "anyang",
//            "anqing",
//            "ankang",
//            "akesu",
//            "anshun",
//            "aletai",
//            "alashan",
//            "aba",
//            "ali",
//            "alaer",
//            "aomen",
//            "bj",
//            "baoding",
//            "binzhou",
//            "baotou",
//            "baoji",
//            "benxi",
//            "bengbu",
//            "beihai",
//            "bayannaoer",
//            "baicheng",
//            "baishan",
//            "bozhou",
//            "bazhong",
//            "baiyin",
//            "baise",
//            "bijie",
//            "bayinguoleng",
//            "baoshan",
//            "boertala",
//            "cd",
//            "cq",
//            "cs",
//            "cc",
//            "changzhou",
//            "cangzhou",
//            "chifeng",
//            "chengde",
//            "changde",
//            "changzhi",
//            "chenzhou",
//            "chuzhou",
//            "chaohu",
//            "chaozhou",
//            "changji",
//            "chizhou",
//            "chuxiong",
//            "chongzuo",
//            "changdu",
//            "chaoyang",
//            "changshu",
//            "cixi",
//            "dl",
//            "dg",
//            "dezhou",
//            "dongying",
//            "daqing",
//            "datong",
//            "dandong",
//            "danzhou",
//            "deyang",
//            "dazhou",
//            "dali",
//            "daxinganling",
//            "dingxi",
//            "dehong",
//            "diqing",
//            "diaoyudao",
//            "eerduosi",
//            "enshi",
//            "ezhou",
//            "fz",
//            "foshan",
//            "fushun",
//            "fuyang",
//            "fuxin",
//            "jxfuzhou",
//            "fangchenggang",
//            "gz",
//            "gy",
//            "gl",
//            "ganzhou",
//            "guangyuan",
//            "guangan",
//            "guigang",
//            "guyuan",
//            "gannan",
//            "ganzi",
//            "guoluo",
//            "hz",
//            "huizhou",
//            "hrb",
//            "hf",
//            "nmg",
//            "hn",
//            "handan",
//            "heze",
//            "hengshui",
//            "huaian",
//            "hengyang",
//            "huludao",
//            "huainan",
//            "hanzhong",
//            "huaihua",
//            "huaibei",
//            "huanggang",
//            "huzhou",
//            "huangshi",
//            "hulunbeier",
//            "heyuan",
//            "hebi",
//            "hegang",
//            "huangshan",
//            "honghe",
//            "hechi",
//            "hami",
//            "heihe",
//            "hezhou",
//            "haixi",
//            "hetian",
//            "haibei",
//            "haidong",
//            "huangnan",
//            "jn",
//            "jining",
//            "jilin",
//            "jinzhou",
//            "jinhua",
//            "jiaxing",
//            "jiangmen",
//            "jingzhou",
//            "jiaozuo",
//            "jinzhong",
//            "jiamusi",
//            "jiujiang",
//            "jincheng",
//            "jingmen",
//            "jixi",
//            "jian",
//            "jieyang",
//            "jingdezhen",
//            "jiyuan",
//            "jiuquan",
//            "jinchang",
//            "jiayuguan",
//            "jiaozhou",
//            "jimo",
//            "km",
//            "kaifeng",
//            "kashi",
//            "kelamayi",
//            "kuerle",
//            "kezilesu",
//            "kunshan",
//            "lz",
//            "xz",
//            "langfang",
//            "linyi",
//            "luoyang",
//            "liaocheng",
//            "liuzhou",
//            "lianyungang",
//            "linfen",
//            "luohe",
//            "liaoyang",
//            "leshan",
//            "luzhou",
//            "luan",
//            "loudi",
//            "laiwu",
//            "longyan",
//            "lvliang",
//            "lishui",
//            "liangshan",
//            "lijiang",
//            "liupanshui",
//            "liaoyuan",
//            "laibin",
//            "lincang",
//            "longnan",
//            "linxia",
//            "linzhi",
//            "mianyang",
//            "mudanjiang",
//            "maoming",
//            "meizhou",
//            "maanshan",
//            "meishan",
//            "nj",
//            "nb",
//            "nn",
//            "nc",
//            "nantong",
//            "nanyang",
//            "nanchong",
//            "neijiang",
//            "nanping",
//            "ningde",
//            "nujiang",
//            "naqu",
//            "pingdingshan",
//            "puyang",
//            "panjin",
//            "putian",
//            "panzhihua",
//            "pingxiang",
//            "pingliang",
//            "puer",
//            "pixian",
//            "qd",
//            "qh",
//            "qinhuangdao",
//            "quanzhou",
//            "qiqihaer",
//            "qingyuan",
//            "qujing",
//            "quzhou",
//            "qingyang",
//            "qitaihe",
//            "qinzhou",
//            "qianjiang",
//            "qiandongnan",
//            "qiannan",
//            "qianxinan",
//            "rizhao",
//            "rikaze",
//            "sh",
//            "sz",
//            "sy",
//            "sjz",
//            "su",
//            "shantou",
//            "shangqiu",
//            "sanya",
//            "suqian",
//            "shaoxing",
//            "shiyan",
//            "siping",
//            "sanmenxia",
//            "shaoyang",
//            "shangrao",
//            "suining",
//            "sanming",
//            "suihua",
//            "shihezi",
//            "ahsuzhou",
//            "shaoguan",
//            "songyuan",
//            "suizhou",
//            "shanwei",
//            "shuangyashan",
//            "shuozhou",
//            "shizuishan",
//            "shangluo",
//            "shennongjia",
//            "shannan",
//            "shuangliu",
//            "tj",
//            "ty",
//            "tangshan",
//            "taian",
//            "zjtaizhou",
//            "jstaizhou",
//            "tieling",
//            "tongliao",
//            "tonghua",
//            "tianshui",
//            "tongling",
//            "tongchuan",
//            "tongren",
//            "tianmen",
//            "tacheng",
//            "tulufan",
//            "tumushuke",
//            "wh",
//            "wx",
//            "xj",
//            "wei",
//            "weifang",
//            "wenzhou",
//            "wuhu",
//            "weinan",
//            "wuhai",
//            "wuzhou",
//            "wulanchabu",
//            "wuwei",
//            "wenshan",
//            "wuzhong",
//            "wujiaqu",
//            "wuzhishan",
//            "xa",
//            "xm",
//            "xn",
//            "xuzhou",
//            "xianyang",
//            "xingtai",
//            "xiangyang",
//            "xinxiang",
//            "xiangtan",
//            "xuchang",
//            "xinyang",
//            "xiaogan",
//            "xinzhou",
//            "xianning",
//            "xinyu",
//            "xuancheng",
//            "xiantao",
//            "xilinguole",
//            "xiangxi",
//            "xingan",
//            "xishuangbanna",
//            "xianggang",
//            "yc",
//            "yichang",
//            "yantai",
//            "yangzhou",
//            "yancheng",
//            "yingkou",
//            "yueyang",
//            "yuncheng",
//            "sxyulin",
//            "yibin",
//            "yangquan",
//            "yanan",
//            "yiyang",
//            "yongzhou",
//            "gxyulin",
//            "jxyichun",
//            "yangjiang",
//            "yanbian",
//            "yuxi",
//            "yili",
//            "yunfu",
//            "hljyichun",
//            "yaan",
//            "yingtan",
//            "yushu",
//            "yiwu",
//            "zz",
//            "zhuhai",
//            "zibo",
//            "zhongshan",
//            "zaozhuang",
//            "zhangjiakou",
//            "zhuzhou",
//            "zhenjiang",
//            "zhoukou",
//            "zhanjiang",
//            "zhumadian",
//            "zhaoqing",
//            "zigong",
//            "zunyi",
//            "zhangzhou",
//            "zhoushan",
//            "zhangye",
//            "ziyang",
//            "zhangjiajie",
//            "zhaotong",
            "zhongwei",
    };


    private static String USER_AGENTS[] = {
            "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1; AcooBrowser; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
            "Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.0; Acoo Browser; SLCC1; .NET CLR 2.0.50727; Media Center PC 5.0; .NET CLR 3.0.04506)",
            "Mozilla/4.0 (compatible; MSIE 7.0; AOL 9.5; AOLBuild 4337.35; Windows NT 5.1; .NET CLR 1.1.4322; .NET CLR 2.0.50727)",
            "Mozilla/5.0 (Windows; U; MSIE 9.0; Windows NT 9.0; en-US)",
            "Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Win64; x64; Trident/5.0; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET CLR 2.0.50727; Media Center PC 6.0)",
            "Mozilla/5.0 (compatible; MSIE 8.0; Windows NT 6.0; Trident/4.0; WOW64; Trident/4.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET CLR 1.0.3705; .NET CLR 1.1.4322)",
            "Mozilla/4.0 (compatible; MSIE 7.0b; Windows NT 5.2; .NET CLR 1.1.4322; .NET CLR 2.0.50727; InfoPath.2; .NET CLR 3.0.04506.30)",
            "Mozilla/5.0 (Windows; U; Windows NT 5.1; zh-CN) AppleWebKit/523.15 (KHTML, like Gecko, Safari/419.3) Arora/0.3 (Change: 287 c9dfb30)",
            "Mozilla/5.0 (X11; U; Linux; en-US) AppleWebKit/527+ (KHTML, like Gecko, Safari/419.3) Arora/0.6",
            "Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.8.1.2pre) Gecko/20070215 K-Ninja/2.1.1",
            "Mozilla/5.0 (Windows; U; Windows NT 5.1; zh-CN; rv:1.9) Gecko/20080705 Firefox/3.0 Kapiko/3.0",
            "Mozilla/5.0 (X11; Linux i686; U;) Gecko/20070322 Kazehakase/0.4.5",
            "Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.8) Gecko Fedora/1.9.0.8-1.fc10 Kazehakase/0.5.6",
            "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/535.11 (KHTML, like Gecko) Chrome/17.0.963.56 Safari/535.11",
            "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_3) AppleWebKit/535.20 (KHTML, like Gecko) Chrome/19.0.1036.7 Safari/535.20",
            "Opera/9.80 (Macintosh; Intel Mac OS X 10.6.8; U; fr) Presto/2.9.168 Version/11.52",
    };


    public  static String getRandomAgents() {
        return USER_AGENTS[new Random().nextInt(USER_AGENTS.length)];
    }


}
